package week4;

public class Terrible{
    public static void main(String[] args) {
        int[] nums=new int[3];

        int total=0;
        int total2=0;
        for(int x=0; x<nums.length; x++){
            for(int y=0;y=1000;y++){
                for(int z=0; z<1000; z++){
                    total += nums[x];
                    total2 += nums[x];
                }
                
            }
        }
    }
}