package week 3;

import java.util.ArrayList;

public class Party{
    private int battlesWon;
    private ArrayList<Character> members;


    //add characters
    //winBattle

    //obj:add headers to characters 
    
    pulic static void main(String[] args){
        Character hero1=new Character();
        Character hero2= ne Character();
        hero1.winBattle(10);
        Party party = new Party();
        party.addCharacter(hero1);
        party.addCharacter(hero2);
        party.winBattle(20);
    }
}